# Generated by Django 4.1.1 on 2022-09-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=5),
            preserve_default=False,
        ),
    ]
