name: Deploy to AWS hosting
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt
    - name: Run Tests'
      env:
        SECRET_KEY: 69tgugtg%^fgJO&*&
        DB_NAME: mydb
        DB_USER: userdb
        DB_PASSWORD: password
        DEBUG_MODE: False
      run: |
        python ./backend/manage.py test
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      SSH_KEY_PATH: ${{ github.workspace }}/../private.key
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
      - name: Update repo
        run: |
          ssh -i $SSH_KEY_PATH ubuntu@api.maksiak.pl "cd /home/ubuntu/gallery_page/backend; ./update_and_restart.sh"
        shell: bash
